name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE: ${{ github.repository_owner }}/marketingtool-frontend  # lowercase
  BACKEND_IMAGE: ${{ github.repository_owner }}/marketingtool-backend    # lowercase

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Convert repository name to lowercase
      run: |
        echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.DEPLOY_TOKEN }}

    - name: Build and push Frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest

    - name: Build and push Backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Create kube config
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy to Kubernetes
      env:
        RDP_HOST: ${{ secrets.RDP_HOST }}
        RDP_USERNAME: ${{ secrets.RDP_USERNAME }}
        RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
      run: |
        kubectl set image deployment/frontend frontend=${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest
        kubectl set image deployment/backend backend=${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest
        kubectl rollout restart deployment frontend
        kubectl rollout restart deployment backend 