name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE: ${{ github.repository }}-frontend
  BACKEND_IMAGE: ${{ github.repository }}-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production  # Add this line to use Production environment
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.DEPLOY_TOKEN }}

    - name: Build and push Frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest

    - name: Build and push Backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Create kube config
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/frontend frontend=${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest
        kubectl set image deployment/backend backend=${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest
        kubectl rollout restart deployment frontend
        kubectl rollout restart deployment backend

    # Added cleanup steps
    - name: Clean up old images from GitHub Container Registry
      if: success()
      run: |
        # Keep only the latest 3 versions of each image
        for image in "${{ env.FRONTEND_IMAGE }}" "${{ env.BACKEND_IMAGE }}"; do
          tags=$(curl -s -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
            "https://api.github.com/user/packages/container/${image}/versions" | \
            jq -r '.[].metadata.container.tags[0]' | sort -r | tail -n +4)
          
          for tag in $tags; do
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
              "https://api.github.com/user/packages/container/${image}/versions/${tag}"
          done
        done

    - name: Clean up old images from Kubernetes nodes
      run: |
        # Remove unused images from nodes
        kubectl get nodes -o=name | xargs -I {} kubectl debug {} -it --image=alpine -- crictl rmi --prune